---
title: "A075A25解析結果"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 増体重量の群間の比較

```{r,setting, echo=FALSE}
pacman::p_load(tidyverse,
               readxl,
               car,
               multcomp,
               broom,
               gt,
               gtsummary,
               ggpubr,
               rstatix)

windowsFonts(Meiryo = windowsFont("Meiryo"))
windowsFonts(Arial = windowsFont("Arial"))
windowsFonts("Yu Gothic" = windowsFont("Yu Gothic"))
```


```{r,weigtht_setting,echo=FALSE}
weight_A25 <- readxl::read_xlsx("weight_A25.xlsx",col_names = TRUE,na = "-")

weight_A25 <- weight_A25 %>%
  filter(!is.na(day10) & !is.na(day20))

weight_A25 <- weight_A25 %>%
  mutate(
    group = factor(group,
                   levels = c(1, 2, 3,4,5,6),
                   labels = c("Control", "Nagano", "Yamaguchi","Oita","Chiba","Miyazaki")))
    
weight_A25 <- weight_A25 %>%
  mutate(
    daily_gain10 = (day10 - day0) / 10,
    daily_gain20 = (day20 - day0) / 20,
    daily_gain10_20 = (day20 - day10) / 10
  )

```

### 10日目から20日目までの１日当たりの増体重量の比較

```{r,echo=FALSE}
# ① 統計計算（Tukey検定）を実行
stat.test <- weight_A25 %>%
  tukey_hsd(daily_gain10_20 ~ group) %>% # ANOVA後のTukey法
  add_y_position()             # グラフ上の描画位置を自動計算

# ② 描画
ggboxplot(weight_A25, x = "group", y = "daily_gain10_20",outlier.shape = NA) +
  geom_jitter(width = 0.15, alpha = 0.6) +
  labs(
    y = "Daily weight gain (g/day)",
    title = "Daily weight gain by group(10日目から20日目の増体)"
  ) +
  theme_bw()+
  stat_pvalue_manual(stat.test, label = "p.adj.signif", hide.ns = TRUE)
```

コントロール群と宮崎株接種群で差が認められた。

```{r,echo=FALSE}
ggplot(weight_A25, aes(x = factor(group), y = daily_gain20)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.15, alpha = 0.6) +
  labs(
    x = "Group",
    y = "Daily weight gain (g/day)",
    title = "Daily weight gain by group(0日目から20日目の増体)"
  ) +
  theme_bw()

ggplot(weight_A25, aes(x = factor(group), y = daily_gain10)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.15, alpha = 0.6) +
  labs(
    x = "Group",
    y = "Daily weight gain (g/day)",
    title = "Daily weight gain by group(0日目から10日目の増体)"
  ) +
  theme_bw()

```

0日目から10日目までの１日当たりの増体重量は各群に傾向はみられない。
10日目から接種菌による影響がみられ始めるのかもしれない。

## 各臓器における菌数測定結果

### 肝臓

```{r liver, echo=FALSE}
cfu_A25_liver <- readxl::read_xlsx("CFU_A25.xlsx",sheet = "liver" ,col_names = TRUE,na = "-")

cfu_A25_liver <- cfu_A25_liver %>%
  mutate(
    group = factor(group,
                   levels = c(1, 2, 3,4,5,6),
                   labels = c("Control", "Nagano", "Yamaguchi","Oita","Chiba","Miyazaki")))
    
cfu_A25_liver <- cfu_A25_liver %>%
  mutate(
    log_CFU = log10((cfu_A25_liver$`CFU/g` + 1))
    )

stat.test_liver <- cfu_A25_liver %>%
  tukey_hsd(log_CFU ~ group) %>% # ANOVA後のTukey法
  add_y_position()             # グラフ上の描画位置を自動計算

# ② 描画
ggboxplot(cfu_A25_liver, x = "group", y = "log_CFU",add = "jitter") +
  labs(
    y = "log CFU/g",
    title = "菌数測定結果(肝臓)"
  ) +
  theme_bw()+
  stat_pvalue_manual(stat.test_liver, label = "p.adj.signif", hide.ns = TRUE)
```

有意差はないが、接種群では高い傾向。

### 心臓

```{r heart, echo=FALSE}
cfu_A25_heart <- readxl::read_xlsx("CFU_A25.xlsx",sheet = "heart" ,col_names = TRUE,na = "-")

cfu_A25_heart <- cfu_A25_heart %>%
  mutate(
    group = factor(group,
                   levels = c(1, 2, 3,4,5,6),
                   labels = c("Control", "Nagano", "Yamaguchi","Oita","Chiba","Miyazaki")))
    
cfu_A25_heart <- cfu_A25_heart %>%
  mutate(
    log_CFU = log10((cfu_A25_heart$`CFU/g` + 1)
  ))

stat.test_heart <- cfu_A25_heart %>%
  tukey_hsd(log_CFU ~ group) %>% # ANOVA後のTukey法
  add_y_position()             # グラフ上の描画位置を自動計算

# ② 描画
ggboxplot(cfu_A25_heart, x = "group", y = "log_CFU",outlier.shape = NA ) +
  geom_jitter(width = 0.15) +
  labs(
    y = "log CFU/g",
    title = "菌数測定結果(心臓)"
  ) +
  theme_bw()+
  stat_pvalue_manual(stat.test_heart, label = "p.adj.signif", hide.ns = TRUE)
```

肝臓と同様の印象。


### 脾臓

```{r spleen, echo=FALSE}
cfu_A25_spleen <- readxl::read_xlsx("CFU_A25.xlsx",sheet = "spleen" ,col_names = TRUE,na = "-")

cfu_A25_spleen <- cfu_A25_spleen %>%
  mutate(
    group = factor(group,
                   levels = c(1, 2, 3,4,5,6),
                   labels = c("Control", "Nagano", "Yamaguchi","Oita","Chiba","Miyazaki")))
    
cfu_A25_spleen <- cfu_A25_spleen %>%
  mutate(
    log_CFU = log10((cfu_A25_spleen$`CFU/g` + 1)
  ))

stat.test_spleen <- cfu_A25_spleen %>%
  tukey_hsd(log_CFU ~ group) %>% # ANOVA後のTukey法
  add_y_position()             # グラフ上の描画位置を自動計算

# ② 描画
ggboxplot(cfu_A25_spleen, x = "group", y = "log_CFU",outlier.shape = NA) +
  geom_jitter(width = 0.15) +
  labs(
    y = "log CFU/g",
    title = "菌数測定結果(脾臓)"
  ) +
  theme_bw()+
  stat_pvalue_manual(stat.test_spleen, label = "p.adj.signif", hide.ns = TRUE)

```

Tukey検定で宮崎株接種で有意に増加。Dunett検定では長野、大分でも有意に増加していた。

<br>

## 病理学的評価


### 心臓

```{r pericarditis,echo = FALSE}
# 1. データの準備
path_peri <- readxl::read_xlsx("A25_病理.xlsx",sheet = "pericarditis",col_names = TRUE) %>%
  mutate(
    total = posi + nega,
    results = paste0(posi," / ", total),
    group = factor(group,
                   levels = c(1, 2, 3,4,5,6),
                   labels = c("Control", "Nagano", "Yamaguchi","Oita","Chiba","Miyazaki")))
dat_path_peri <- as.matrix(path_peri[, c("posi", "nega")])
rownames(dat_path_peri) <- path_peri$group

path_peri %>%
  gt() %>%
  cols_label(
    posi = "病変あり",
    nega = "病変なし",
    total = "羽数",
    results = "発生率"
  ) %>%
  tab_spanner(columns = posi:nega, label = "心外膜炎")
```

宮崎株接種では高確率に心外膜炎が発生していた。大分株、千葉株でも高頻度に認められた。

